# Generated by Django 4.1 on 2023-03-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='related_proj_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
