# Generated by Django 4.1 on 2023-05-29 16:18
#
# Edited when the blog app was removed. Author originally lived in the blog
# app (table "blog_author"). It now belongs to events, so this migration
# creates it here under the same table name. Databases that already applied
# this migration keep their existing blog_author table unchanged; migration
# 0008 then renames it to events_author and deletes the leftover blog data.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_related_proj_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('personal_website', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog_author',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.author'),
        ),
    ]
