# Generated by Django 4.1 on 2023-05-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_email_author_personal_website'),
        ('events', '0002_events_related_proj_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
