# Generated by Django 4.1 on 2023-06-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='related_proj_team',
        ),
    ]
