# Generated by Django 4.1 on 2023-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_related_proj_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='related_proj_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
