# Generated by Django 4.1 on 2024-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_related_proj_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='image_prepend_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='photo_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='total_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
