# Generated by Django 4.1 on 2024-10-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_folder_name_events_image_prepend_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
