# Generated by Django 4.1 on 2023-06-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_email_author_personal_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='raw_blog_path',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='related_proj_team',
        ),
    ]
