# Generated by Django 4.1 on 2023-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_raw_blog_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_proj_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
