# Generated by Django 4.1 on 2023-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketdata',
            name='motor_brand',
            field=models.CharField(choices=[('1', 'Apogee'), ('2', 'Estes'), ('3', 'Quest'), ('4', 'AeroTech'), ('5', 'Cesaroni'), ('6', 'Loki Research')], max_length=4),
        ),
    ]
