# Generated by Django 4.1 on 2023-09-03 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_rocketdata_motor_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('impulse_class', models.CharField(max_length=4)),
                ('thrust_source', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('burnout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grain_separation', models.IntegerField(default=0)),
                ('grain_density', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grain_initialinnerradius', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grain_initialheight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nozzle_radius', models.DecimalField(decimal_places=2, max_digits=4)),
                ('throat_radius', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rocketmaterial',
            name='rocket',
        ),
        migrations.DeleteModel(
            name='RocketData',
        ),
        migrations.DeleteModel(
            name='RocketMaterial',
        ),
    ]
