# Generated by Django 4.1 on 2023-01-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(db_index=True, max_length=255)),
                ("last_name", models.CharField(db_index=True, max_length=255)),
                ("picture", models.URLField(unique=True)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Please add alternative text",
                        max_length=255,
                        null=True,
                        verbose_name="Alternative text",
                    ),
                ),
                (
                    "seds_role",
                    models.CharField(
                        choices=[
                            ("Chair of the Board", "Chair of the Board"),
                            ("President", "President"),
                            ("Vice President", "Vice President"),
                            ("Communications Officer", "Communications Officer"),
                            ("Events Coordinator", "Events Coordinator"),
                            ("Mars Senator", "Mars Senator"),
                            ("Jupiter Senator", "Jupiter Senator"),
                            ("Saturn Senator", "Saturn Senator"),
                            ("Rocketry Lead", "Rocketry Lead"),
                            ("CubeSat Lead", "CubeSat Lead"),
                            ("Radio Telescope Lead", "Radio Telescope Lead"),
                            ("Astrophotography Lead", "Astrophotography Lead"),
                            ("Mars Rover Lead", "Mars Rover Lead"),
                            ("Weather Balloon Lead", "Weather Balloon Lead"),
                            ("Webmaster", "Webmaster"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "active_years",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2018-2019", "2018-2019"),
                            ("2019-2020", "2019-2020"),
                            ("2021-2022", "2021-2022"),
                            ("2022-2023", "2022-2023"),
                            ("2023-2024", "2023-2024"),
                            ("2024-2025", "2024-2025"),
                            ("2025-2026", "2025-2026"),
                        ],
                        max_length=18,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("linkedin", models.URLField(blank=True)),
                ("personal_site", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "SEDS Executive Members",
            },
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseSEDSMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounts",
                "verbose_name_plural": "Accounts",
            },
        ),
    ]
