# Generated by Django 4.1 on 2023-01-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execmembers',
            name='club_chapter_role',
            field=models.CharField(blank=True, choices=[('Rocketry Lead', 'Rocketry Lead'), ('CubeSat Lead', 'CubeSat Lead'), ('Radio Telescope Lead', 'Radio Telescope Lead'), ('Astrophotography Lead', 'Astrophotography Lead'), ('Mars Rover Lead', 'Mars Rover Lead'), ('Weather Balloon Lead', 'Weather Balloon Lead')], max_length=24),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='active_years',
            field=models.CharField(blank=True, choices=[('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=24),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='seds_role',
            field=models.CharField(blank=True, choices=[('Chair of the Board', 'Chair of the Board'), ('President', 'President'), ('Vice President', 'Vice President'), ('Communications Officer', 'Communications Officer'), ('Events Coordinator', 'Events Coordinator'), ('Mars Senator', 'Mars Senator'), ('Jupiter Senator', 'Jupiter Senator'), ('Saturn Senator', 'Saturn Senator'), ('Webmaster', 'Webmaster'), ('Chair of the Board, Vice President', 'Chair of the Board, Vice President')], max_length=64),
        ),
    ]
