# Generated by Django 4.1 on 2023-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_execmembers_club_chapter_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execmembers',
            name='active_years',
            field=models.CharField(blank=True, choices=[('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='club_chapter_role',
            field=models.CharField(blank=True, choices=[('Rocketry Lead', 'Rocketry Lead'), ('Weather Balloon Lead', 'Weather Balloon Lead'), ('Astrophotography Lead', 'Astrophotography Lead'), ('CubeSat Lead', 'CubeSat Lead'), ('Radio Telescope Lead', 'Radio Telescope Lead'), ('Mars Rover Lead', 'Mars Rover Lead')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='personal_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='seds_role',
            field=models.CharField(blank=True, choices=[('Chair of the Board, Vice President', 'Chair of the Board, Vice President'), ('Chair of the Board', 'Chair of the Board'), ('President', 'President'), ('Vice President', 'Vice President'), ('Director of Finance', 'Director of Finance'), ('Secretary', 'Secretary'), ('Communications Officer', 'Communications Officer'), ('Event Coordinator', 'Event Coordinator'), ('Mars Senator', 'Mars Senator'), ('Jupiter Senator', 'Jupiter Senator'), ('Saturn Senator', 'Saturn Senator'), ('Webmaster', 'Webmaster')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
