# Generated by Django 4.1 on 2023-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_execmembers_active_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='basesedsmember',
            name='chapter_affiliation',
            field=models.ManyToManyField(to='main.chapters'),
        ),
    ]
