# Generated by Django 4.1 on 2023-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chapters_basesedsmember_chapter_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesedsmember',
            name='project_lead',
            field=models.BooleanField(default=False),
        ),
    ]
