# Generated by Django 4.1 on 2023-09-04 07:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_basesedsmember_project_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execmembers',
            name='active_years',
        ),
        migrations.RemoveField(
            model_name='execmembers',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='execmembers',
            name='club_chapter_role',
        ),
        migrations.RemoveField(
            model_name='execmembers',
            name='seds_role',
        ),
        migrations.RemoveField(
            model_name='execmembers',
            name='twitter',
        ),
        migrations.AddField(
            model_name='execmembers',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execmembers',
            name='year_and_chapter_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='execmembers',
            name='year_and_eboard_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
