# Generated by Django 4.1 on 2023-09-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_execmembers_active_years_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execmembers",
            name="year_and_chapter_role",
        ),
        migrations.RemoveField(
            model_name="execmembers",
            name="year_and_eboard_role",
        ),
        migrations.AddField(
            model_name="execmembers",
            name="year_and_chapter_role",
            field=models.JSONField(null=True, default=dict),
        ),
        migrations.AddField(
            model_name="execmembers",
            name="year_and_eboard_role",
            field=models.JSONField(null=True, default=dict),
        ),
    ]
