# Generated by Django 4.1 on 2023-09-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_execmembers_year_and_chapter_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearAndRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(db_index=True, max_length=255)),
                ('is_eboard', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='execmembers',
            name='year_and_chapter_role',
        ),
        migrations.AddField(
            model_name='execmembers',
            name='seds_roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.yearandrole'),
        ),
    ]
