# Generated by Django 4.1 on 2023-09-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_yearandrole_remove_execmembers_year_and_chapter_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execmembers',
            name='year_and_eboard_role',
        ),
    ]
