# Generated by Django 4.1 on 2023-09-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_execmembers_year_and_eboard_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execmembers',
            name='seds_roles',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.yearandrole'),
        ),
    ]
