# Generated by Django 4.1 on 2023-09-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_execmembers_seds_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execmembers',
            name='seds_roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.yearandrole'),
        ),
    ]
