# Generated by Django 4.1 on 2023-09-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_execmembers_seds_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execmembers',
            name='seds_roles',
        ),
        migrations.AddField(
            model_name='yearandrole',
            name='seds_member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.execmembers'),
        ),
    ]
