# Generated by Django 4.1 on 2023-09-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_execmembers_seds_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearandrole',
            name='seds_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.execmembers'),
        ),
    ]
