# Generated by Django 4.1 on 2023-09-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_yearandrole_seds_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AstrophotographyPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, null=True)),
                ('iso', models.CharField(max_length=64)),
                ('focal_length', models.CharField(max_length=64)),
                ('aperture', models.CharField(max_length=64)),
                ('exposure_time', models.CharField(max_length=64)),
                ('camera_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cameramodel')),
            ],
        ),
    ]
