# Generated by Django 4.1 on 2023-09-12 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cameramodel_astrophotographyphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
