# Generated by Django 4.1 on 2023-09-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_astrophotographyphotos_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astrophotographyphotos',
            options={'verbose_name': 'Astrophotography Photos', 'verbose_name_plural': 'Astrophotography Photos'},
        ),
        migrations.RemoveField(
            model_name='astrophotographyphotos',
            name='camera_model',
        ),
        migrations.AddField(
            model_name='cameramodel',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.astrophotographyphotos'),
            preserve_default=False,
        ),
    ]
