# Generated by Django 4.1 on 2023-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_astrophotographyphotos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='homepage_active',
            field=models.BooleanField(default=False),
        ),
    ]
