# Generated by Django 4.1 on 2023-09-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_astrophotographyphotos_homepage_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramodel',
            name='photo',
        ),
        migrations.AlterField(
            model_name='astrophotographyphotos',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cameramodel'),
        ),
    ]
