# Generated by Django 4.1 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_cameramodel_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='camera_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cameramodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='astrophotographyphotos',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
