# Generated by Django 4.1 on 2023-09-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_astrophotographyphotos_camera_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lens', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='guiding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='target',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='tracker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astrophotographyphotos',
            name='exposure_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='astrophotographyphotos',
            name='camera_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cameradata'),
        ),
        migrations.DeleteModel(
            name='CameraModel',
        ),
    ]
