# Generated by Django 4.1 on 2023-09-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_cameradata_astrophotographyphotos_date_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
