# Generated by Django 4.1 on 2024-03-29 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_astrophotographyphotos_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='execmembers',
            name='picture',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
