# Generated by Django 4.1 on 2024-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_mailinglist_created_alter_execmembers_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearandrole',
            name='is_project_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='astrophotographyphotos',
            name='photo',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
