# Generated by Django 4.1 on 2024-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_yearandrole_is_project_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrophotographyphotos',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
