"""
Django settings for tuftsseds project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/

Note: There are various settings here that are set depending on the value of 
the variable constant DEBUG. When DEBUG = True, settings meant for production are
used. When DEBUG = False, settings meant for a development envionment are used. 
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production (which will likely never happen so
#   long as you follow the merging strategy)!
# In the case you must make "DEBUG = False" while running things on your local machine, this will be so
#   that you can make run django commands to make changes to the database using the Railway client.
DEBUG = os.environ.get("DEBUG", "True") == "True"
WHITENOISE_AUTOREFRESH = False

if not DEBUG:
    ALLOWED_HOSTS = [
        "django-server-production-0e38.up.railway.app",
        "https://sedstufts.org",
        "sedstufts.org",
    ]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "127.0.0.1:8000"]

INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition
INSTALLED_APPS = [
    # "debug_toolbar",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "tuftsseds.siteapps.main.apps.MainConfig",
    "tuftsseds.siteapps.blog.apps.BlogConfig",
    "tuftsseds.siteapps.events.apps.EventsConfig",
    "tuftsseds.siteapps.database.apps.DatabaseConfig",
    "tuftsseds.siteapps.account.apps.AccountConfig",
    "taggit",
    # "django_crontab",
    "django_extensions",
]
if DEBUG:
    INSTALLED_APPS.insert(0, "whitenoise.runserver_nostatic")

SECRET_KEY = os.environ["SECRET_KEY"]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# this setting is mainly for the django debug toolbar
if DEBUG:
    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)


ROOT_URLCONF = "tuftsseds.tuftsseds_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tuftsseds.tuftsseds_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

REGULAR_DB = os.environ.get("REGULAR_DB", "False") == "True"

if DEBUG and REGULAR_DB:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": os.environ["PGDATABASE"],
            "USER": os.environ["PGUSER"],
            "PASSWORD": os.environ["PGPASSWORD"],
            "HOST": os.environ["PGHOST"],
            "PORT": os.environ["PGPORT"],
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"


AUTH_USER_MODEL = "main.BaseSEDSMember"
LOGIN_REDIRECT_URL = "/account/dashboard/"
LOGIN_URL = "/account/login-register/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# runs the cron job every Saturday at 11:59
# read https://en.wikipedia.org/wiki/Cron#Format for more info
CRONJOBS = [
    (
        "59 23 * * 6",
        "tuftsseds.siteapps.main.deactivate_execs.check_and_deactivate_active_members",
    )
]

# Directory for files for blogs

# Django-taggit settings
TAGGIT_CASE_INSENSITIVE = True

# Other
ACTIVE_YEAR = "2025-2026"

# Used for creating visual DB schemas
GRAPH_MODELS = {
    "all_applications": True,
    "graph_models": True,
}